import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import TimeAgo from 'javascript-time-ago'

import en from 'javascript-time-ago/locale/en.json'
import ru from 'javascript-time-ago/locale/ru.json'


export default function Home() {
  TimeAgo.addDefaultLocale(en)
TimeAgo.addLocale(ru)
  return (
    <div >
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar/>

      
    </div>
  )
}
